{% set name = "codebraid" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f24f028767504121bcd58eea9d105e715897cc53bc7d6060b1d935b25e5352f4

build:
  noarch: python
  number: 0
  entry_points:
    - codebraid = codebraid.cmdline:main
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - bespon >=0.3
    - python >=3.5

test:
  imports:
    - codebraid
    - codebraid.codeprocessors
    - codebraid.converters
  commands:
    - codebraid --help

about:
  home: http://github.com/gpoore/codebraid
  license: BSD 3-Clasue
  license_family: BSD
  license_file: LICENSE.txt
  summary: Live code in Pandoc Markdown
  description: |
    Codebraid is a Python program that enables executable code in Pandoc Markdown
    documents. Using Codebraid can be as simple as adding a class to your code
    blocks' attributes, and then running codebraid rather than pandoc to convert
    your document from Markdown to another format. codebraid supports almost all
    of pandoc's options and passes them to pandoc internally.
  doc_url: https://github.com/gpoore/codebraid
  dev_url: https://github.com/gpoore/codebraid

extra:
  recipe-maintainers:
    - mwcraig
    - gpoore
