{% set name = "codebraid" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c739b133b3d8d16766b0c38a93c129db3df69072ef796de9714e357e5f1135d

build:
  noarch: python
  number: 0
  entry_points:
    - codebraid = codebraid.cmdline:main
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bespon >=0.6
    - python >=3.7

test:
  imports:
    - codebraid
    - codebraid.codeprocessors
    - codebraid.converters
  commands:
    - codebraid --help

about:
  home: http://github.com/gpoore/codebraid
  license: BSD-3-Clasue
  license_family: BSD
  license_file: LICENSE.txt
  summary: Live code in Pandoc Markdown
  description: |
    Codebraid is a Python program that enables executable code in Pandoc Markdown
    documents. Using Codebraid can be as simple as adding a class to your code
    blocks' attributes, and then running codebraid rather than pandoc to convert
    your document from Markdown to another format. codebraid supports almost all
    of pandoc's options and passes them to pandoc internally.
  doc_url: https://github.com/gpoore/codebraid
  dev_url: https://github.com/gpoore/codebraid

extra:
  recipe-maintainers:
    - mwcraig
    - gpoore
