travis:
  secure:
    BINSTAR_TOKEN: GgHMVLYND3wmmS23wN0gnm2TD9cUkdriBqBjsBTrBM+rRr1PhGbAePKxHYPHFtehfUEZdzBr9AidgSdxz5oqlDry1c35ezQady5Z2XYS/83fINOTkzRsiSMlCkrf5fE73Q4BGvEIdbLh6su6Ia0jdi+BblzgyYeSEB6pi8RvYfF0ZG7Uj0UeeGYEaGD41tBFz7KQ7gKAP4cpCFBPG+8IUSW7KIvIu7Uh16YzzGWTuh3jCVg9GOZtTGWGvbQNZ88uD/RaSQjkQL6kUfKxOyrLexeNzQlz21GshqYbn/4Orjqz2VmKWP4icHsVFfdLNDFu342IZFMVIrbpIODhqKg5/oDGEyXgzgjGOWyYt0WHcMeIvVdSuvPUksRab/d6kLjm6jF2XSUDP1GB6EDMtIT5E2gNG79OfE6JH65I6Cfk61bG+2Cnk2tdTaZFF44Bl7pGC9B890mIQtLhlhFaCXcyQS7UdksiCXJGwMFJmKPZpbQoYURRVCM94i20j6oMiJxJ04hODgYn728WI2+s5vLUOampOHoY+FVYCQPMRtvA8L9tFUcLCd3mqYhnA5PLs/77t4OJd0c4WyHuUlglmoqU4V/f4zUv8n+curInWknSciL7CKIVS5OxzfABgra17LcyOfYOZQ9gJsce3o6mhYBkcGGuQoyc2sySWtQDUJkh0MI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
